/**
 * 描述：模块注册js,name为模块名，模块名不能重复，
 * @author 吴明坤
 */
;(function(){
	
	var modules=[
		//组件
		{
			name:'AddComTable',
			js:'widget/add-com-table.js'
		},
		{
			name:'Table',
			js:'widget/newtec.table.js'
		},
		{
			name:'TableExt',
			js:'widget/newtec.tableext.js'
		},
		{
			name:'Calendar',
			js:'widget/newtec.calendar.js'
		},
		{
			name:'CanvasVertor',
			js:'widget/newtec.canvasVertor.js'
		},
		{
			name:'CanvasVertor2',
			js:'widget/newtec.canvasVertor2.js'
		},
		{
			name:'Canvg',
			js:'widget/newtec.canvg.js'
		},
		{
			name:'Percent',
			js:'widget/newtec.chart.js'
		},
		{
			name:'Circularchart',
			js:'widget/newtec.circularchart.js'
		},
		{
			name:'Ckeditor',
			js:'widget/newtec.ckeditor.js'
		},
		{
			name:'CodeEditor',
			js:'widget/newtec.codeeditor.js'
		},
		{
			name:'Columnchart',
			js:'widget/newtec.columnchart.js'
		},
		{
			name:'DateTime',
			js:'widget/newtec.datetime.js'
		},
		{
			name:'Doubletable',
			js:'widget/newtec.doubletable.js'
		},
		{
			name:'DsWidget',
			js:'widget/newtec.dswidget.js'
		},
		{
			name:'Echarts',
			js:'widget/newtec.echarts.js'
		},
		{
			name:'Fetch',
			js:'widget/newtec.fetch.js'
		},
		{
			name:'File',
			js:'widget/newtec.file.js'
		},
		{
			name:'Form',
			js:'widget/newtec.form.js'
		},
		{
			name:'FormItem',
			js:'widget/newtec.formitem.js'
		},
		{
			name:'HoneySwitch',
			js:'widget/newtec.honeySwitch.js'
		},
		{
			name:'AutoComplete',
			js:'widget/newtec.jqui.js'
		},
		{
			name:'Jsmind',
			js:'widget/newtec.jsmind.js'
		},
		{
			name:'Lightgallery',
			js:'widget/newtec.lightgallery.js'
		},
		{
			name:'Menu',
			js:'widget/newtec.menu.js'
		},
		{
			name:'MenuExt',
			js:'widget/newtec.menuExt.js'
		},
		{
			name:'MyCanvas',
			js:'widget/newtec.mycanvas.js'
		},
		{
			name:'MyText',
			js:'widget/newtec.myformItem.js'
		},
		{
			name:'MySelect',
			js:'widget/newtec.myselect.js'
		},
		{
			name:'MySelect2',
			js:'widget/newtec.myselect2.js'
		},
		{
			name:'TopNav',
			js:'widget/newtec.nav.js'
		},
		{
			name:'NewMenu',
			js:'widget/newtec.newMenu.js'
		},
		{
			name:'Pagin',
			js:'widget/newtec.pagin.js'
		},
		{
			name:'Pagin2',
			js:'widget/newtec.pagin2.js'
		},
		{
			name:'Paragraph',
			js:'widget/newtec.paragraph.js'
		},
		{
			name:'ProcessDigram',
			js:'widget/newtec.processDigram.js'
		},
		{
			name:'ProcessNode',
			js:'myqdp/js/widget/newtec.processNode.js'
		},
		{
			name:'ProcessNodeSimple',
			js:'widget/newtec.processNodeSimple.js'
		},
		{
			name:'Progress',
			js:'widget/newtec.progress.js'
		},
		{
			name:'Question',
			js:'myqdp/js/widget/newtec.question.js'
		},
		{
			name:'QuestionBook',
			js:'widget/newtec.questionBook.js'
		},
		{
			name:'QuestionEdit',
			js:'widget/newtec.questionEdit.js'
		},
		{
			name:'RaphaelVertor',
			js:'widget/newtec.raphaelVertor.js'
		},
		{
			name:'ResultAdapter',
			js:'widget/newtec.resultadapter.js'
		},
		{
			name:'Select',
			js:'widget/newtec.select.js'
		},
		{
			name:'SimpleSearchInput',
			js:'widget/newtec.simpleSearchInput.js'
		},
		{
			name:'SlideBox',
			js:'widget/newtec.slidebox.js'
		},
		{
			name:'Splinechart',
			js:'widget/newtec.splinechart.js'
		},
		{
			name:'Tree',
			js:'widget/newtec.tree.js'
		},
		{
			name:'TreeGrid',
			js:'widget/newtec.treegrid2.0.js'
		},
		{
			name:'Upload',
			js:'widget/newtec.upload.js'
		},
		{
			name:'Webuploader',
			js:'widget/newtec.webuploader.js'
		},
		{
			name:'Widget',
			js:'widget/newtec.widget.js'
		},

		{
			name:"Params",
			js:'param/newtec.params.js'
		},
		//页面
		{
			name:"Compage",
			js:'page/widget/newtec.compage.js'
		},
		{
			name:"SearchPage",
			js:'page/widget/newtec.searchpage.js'
		},
		{
			name:"AreaTreepage",
			js:'page/newtec.areaTreepage.js'
		},
		{
			name:"CreateTable",
			js:'page/newtec.createTable.js'
		},
		{
			name:"dataSourcePage",
			js:'page/newtec.datasource2edit.js'
		},
		{
			name:"DefutPage",
			js:'page/newtec.defutpage.js'
		},
		{
			name:"EntityPage",
			js:'page/newtec.entitypage.js'
		},
		{
			name:"FilePage",
			js:'page/newtec.filepage.js'
		},
		{
			name:"Many2ManyPage",
			js:'page/newtec.many2manypage.js'
		},
		{
			name:"CompMany2ManyPage",
			js:'page/newtec.many2manypage2.js'
		},
		{
			src:"CompMany2ManyPage",
//			js:{ResMany2ManyPage:"newtec.many2manypage3.js","ResMany2ManyPage2":"newtec.many2manypage5.js"}
			js:'page/newtec.many2manypage3.js'
		},
		{
			name:"MenuPage",
			js:'page/newtec.menupage.js'
		},
		{
			name:"NodePage",
			js:'page/newtec.nodepage.js'
		},
		{
			name:"PagePage",
			js:'page/newtec.pagepage.js'
		},
		{
			name:"PageDefPage",
			js:'page/newtec.pagepage3.js'
		},
		{
			name:"ParamPage",
			js:'page/newtec.param.js'
		},
		{
			name:"RolePage",
			js:'page/newtec.rolepage.js'
		},
		{
			name:"SearchExtendPage",
			js:'page/newtec.searchextend.js'
		},
		{
			name:"TreePage",
			js:'page/newtec.treepage.js'
		}]
	Newtec.addModules(modules)
})();


